# Generated by Django 6.0.6 on 2026-08-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=40, unique=True)),
                ('mtTotal', models.FloatField(null=True)),
                ('mtttc', models.FloatField(null=True)),
                ('tauxTVA', models.FloatField(null=True)),
                ('qunatité', models.FloatField(null=True)),
                ('validation', models.BooleanField(default=False)),
            ],
        ),
    ]
