# Generated by Django 6.0.6 on 2026-08-14 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
        ('product', '0003_product_id_categorie_product_id_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product'),
        ),
    ]
