# Generated by Django 6.0.6 on 2026-08-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_commande_id_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='qunatité',
            new_name='qunatite',
        ),
    ]
